- name: Create temp directory
  file:
    path: "/tmp/{{ role_name }}"
    state: directory
  register: directory
  tags:
    - deploy
    - destroy

- name: Create Helm files
  template:
    src: "{{ role_path }}/templates/tmp/{{ role_name }}/{{ item }}.j2"
    dest: "{{ directory.path }}/{{ item }}"
  with_items:
    - values.yaml
  tags:
    - deploy
    - destroy

- name: Apply chart
  shell: "helm upgrade {{ role_name }} consul --install --values {{ directory.path }}/values.yaml --repo https://helm.releases.hashicorp.com"
  tags:
    - deploy

- name: Delete chart
  shell: "helm uninstall {{ role_name }}"
  tags:
    - destroy
