- name: Get binary stats
  stat:
    path: /usr/local/bin/istioctl
  register: binary

- name: Download archive
  get_url:
    url: "https://github.com/istio/istio/releases/download/{{ istio_version }}/istioctl-{{ istio_version }}-linux-amd64.tar.gz"
    dest: "/tmp/istioctl-{{ istio_version }}-linux-amd64.tar.gz"
  register: archive
  when: binary.stat.exists == false

- name: Extract archive
  unarchive:
    src: "{{ archive.dest }}"
    remote_src: yes
    dest: /tmp
  when: binary.stat.exists == false

- name: Copy binary
  copy:
    src: /tmp/istioctl
    remote_src: yes
    dest: /usr/local/bin
    owner: root
    group: root
    mode: "0755"
  when: binary.stat.exists == false
  become: yes
