- name: Install kubeadm, kubelet and kubectl
  apt:
    name:
      - kubeadm={{ kubeadm_version }}
      - kubelet={{ kubeadm_version }}
      - kubectl={{ kubeadm_version }}
    state: present
  become: yes

- name: Hold kubeadm, kubelet and kubectl
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  become: yes
  with_items:
    - kubeadm
    - kubelet
    - kubectl
