- name: Enable iptables to see IPv4 traffic
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    sysctl_file: /etc/sysctl.d/k8s.conf
    state: present
  become: yes

- name: Enable iptables to see IPv6 traffic
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: "1"
    sysctl_file: /etc/sysctl.d/k8s.conf
    state: present
  become: yes
