---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pi-hole
  labels:
    app.kubernetes.io/name: pi-hole
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  rules:
    - host: pi-hole.apps.fdavidson.net
      http:
        paths:
          - path: /
            backend:
              serviceName: pi-hole
              servicePort: http
