---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pi-hole
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
spec:
  rules:
    - host: pi-hole.apps.fdavidson.net
      http:
        paths:
          - path: /
            backend:
              serviceName: pi-hole
              servicePort: http
