---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi-hole-data
  labels:
    app.kubernetes.io/name: pi-hole
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    volume.beta.kubernetes.io/storage-class: vsphere
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
