---
apiVersion: v1
kind: Service
metadata:
  name: pi-hole
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: dns-tcp
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: dns-udp
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
