- name: Common
  hosts:
    - kube_master
    - kube_workers
  roles:
    - common

- name: Kube master
  hosts:
    - kube_master
  roles:
    - kube-master

- name: Kube workers
  hosts:
    - kube_workers
  roles:
    - kube-worker

- name: Infrastructure
  hosts:
    - kube_master
  roles:
    - vsphere-storage
    - flannel
    - metallb
    - metrics-server
    - istio-operator
    - couchbase-operator
    - eck-operator

- name: Tools
  hosts:
    - kube_master
  roles:
    - helm
