- name: Common
  hosts:
    - kube_master
    - kube_workers
  roles:
    - common

- name: Kube master
  hosts:
    - kube_master
  roles:
    - kube-master

- name: Kube workers
  hosts:
    - kube_workers
  roles:
    - kube-worker
  serial: "{{ 0 if ansible_check_mode else 1 }}"

- name: Infrastructure
  hosts:
    - kube_master
  roles:
    - vsphere-storage
    - flannel
    - metallb
    - istio

- name: Tools
  hosts:
    - kube_master
  roles:
    - helm
