- name: Download Metal namespace
  get_url:
    url: "https://raw.githubusercontent.com/metallb/metallb/v{{ metal_lb_version }}/manifests/namespace.yaml"
    dest: /tmp/namespace.yaml
  register: metallb_namespace

- name: Apply Metal namespace
  k8s:
    src: "{{ metallb_namespace.dest }}"
    wait: yes
    state: present

- name: Apply Metal secret
  k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: memberlist
        namespace: metallb-system
      type: Opaque
      data:
        secretkey: NDRnR2p0NU9manVwbDZYRlZDVDhTdTc2MkJ2dWVrVDlXalVtUUlDUGRlSzJxeVhPaHEwTHRBcFM1S1RqZWlqeApuMDdSQkZSc09iNE42TE9vNWh4RXJoM0pDNCtzN2xGRFQ2eThCNnk5L3NwOTE1dVZPdGk5WU5nUTR4eGlqOHVrCnROTTRmZDlJOUNBUFlkWGs0d2thRk8ycmtqeGNhZklUd1VjQWk5TmFQaFE9
    wait: yes
    state: present

- name: Apply Metal config map
  k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: config
        namespace: metallb-system
      data:
        config: |
          address-pools:
            - name: default
              protocol: layer2
              addresses:
                - 192.168.225.24-192.168.225.29
    wait: yes
    state: present

- name: Download Metal manifest
  get_url:
    url: "https://raw.githubusercontent.com/metallb/metallb/v{{ metal_lb_version }}/manifests/metallb.yaml"
    dest: /tmp/metallb.yaml
  register: metallb_manifest

- name: Apply Metal manifest
  k8s:
    src: "{{ metallb_manifest.dest }}"
    wait: yes
    state: present
