- name: Download Metal manifests
  get_url:
    url: "https://raw.githubusercontent.com/metallb/metallb/v{{ metal_lb_version }}/manifests/{{ item }}"
    dest: "/tmp/{{ item }}"
  register: flannel_manifest
  with_items:
    - namespace.yaml
    - metallb.yaml

- name: Apply Metal manifests
  k8s:
    src: "/tmp/{{ item }}"
    state: present
  with_items:
    - namespace.yaml
    - metallb.yaml

- name: Apply Metal secret
  k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: memberlist
        namespace: metallb-system
      type: Opaque
      data:
        secretkey: NDRnR2p0NU9manVwbDZYRlZDVDhTdTc2MkJ2dWVrVDlXalVtUUlDUGRlSzJxeVhPaHEwTHRBcFM1S1RqZWlqeApuMDdSQkZSc09iNE42TE9vNWh4RXJoM0pDNCtzN2xGRFQ2eThCNnk5L3NwOTE1dVZPdGk5WU5nUTR4eGlqOHVrCnROTTRmZDlJOUNBUFlkWGs0d2thRk8ycmtqeGNhZklUd1VjQWk5TmFQaFE9

- name: Apply Metal config map
  k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: config
        namespace: metallb-system
      data:
        config: |
          address-pools:
            - name: default
              protocol: layer2
              addresses:
                - 192.168.225.24-192.168.225.29
    state: present
