---
apiVersion: v1
kind: Secret
metadata:
  name: couchbase-elasticsearch-connector-secrets
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
data:
  couchbase-password.toml: {{ .Values.couchbase.passwordFileContent | b64enc }}
  elasticsearch-password.toml: {{ .Values.elasticsearch.passwordFileContent | b64enc }}
  truststore-password.toml: {{ .Values.elasticsearch.truststorePasswordFileContent | b64enc }}
