---
apiVersion: v1
kind: Service
metadata:
  name: couchbase-elasticsearch-connector
  labels:
    app: {{ .Chart.Name }}
    cbes-group: default
    version: {{ .Chart.Version }}
spec:
  selector:
    app: {{ .Chart.Name }}
    cbes-group: default
  clusterIP: None
  ports:
    - name: metrics
      port: 31415
