---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}-certificate"
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
type: Opaque
data:
  tls.crt: {{ .Values.certificate.crt | b64enc }}
  tls.key: {{ .Values.certificate.key | b64enc }}
