---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
spec:
  selector:
    app: {{ .Chart.Name }}
  type: LoadBalancer
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
