---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-es-elastic-user
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
type: Opaque
data:
  elastic: {{ .Values.admin.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-es-certs
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
type: Opaque
data:
  ca.crt: {{ .Values.certificates.ca | b64enc }}
  tls.crt: {{ .Values.certificates.crt | b64enc }}
  tls.key: {{ .Values.certificates.key | b64enc }}
