- name: Get kubelet conf stats
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Get kubeadm discovery data
  shell: "kubectl -n kube-public get configmap cluster-info -o jsonpath='{.data.kubeconfig}'"
  delegate_to: "{{ groups['kube_master'][0] }}"
  register: kubectl_discovery_data
  when: not kubelet_conf.stat.exists

- name: Create discovery.yml file
  copy:
    content: "{{ kubectl_discovery_data.stdout }}"
    dest: /etc/kubernetes/discovery.yml
  when: not kubelet_conf.stat.exists
  become: yes

- name: Get kubeadm token
  shell: kubeadm token create
  register: kubeadm_token
  delegate_to: "{{ groups['kube_master'][0] }}"
  delegate_facts: yes
  when: not kubelet_conf.stat.exists

- name: Create join.yml file
  template:
    src: "{{ role_path }}/templates/etc/kubernetes/join.yml.j2"
    dest: /etc/kubernetes/join.yml
    mode: "0644"
    owner: root
    group: root
  vars:
    token: "{{ kubeadm_token.stdout }}"
  when: not kubelet_conf.stat.exists
  become: yes

- name: Gather kube_master facts
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: yes
  when: not kubelet_conf.stat.exists
  with_items: "{{ groups['kube_master'] }}"

- name: Join cluster
  shell: "kubeadm join --config /etc/kubernetes/join.yml"
  when: not kubelet_conf.stat.exists
  become: yes
