admin:
  password: password
certificates:
  ca: |
    -----BEGIN CERTIFICATE-----
    MIIDKjCCAhagAwIBAgIQlJertiCFn4BKs57+T7k0YTAJBgUrDgMCHQUAMBoxGDAW
    BgNVBAMTD0FpcmhlYWQgUm9vdCBDQTAeFw0xMzA1MjcxMDAyMDZaFw0zOTEyMzEy
    MzU5NTlaMC4xLDAqBgNVBAMTI0FpcmhlYWQgRGV2ZWxvcG1lbnQgSW50ZXJtZWRp
    YXRlIENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmS2yhMmmTEFV
    D/yH3jrSy+Rp+c85GuxupfE1r49R6R1hH9HRwLlFKy/9lyqFpyfAg58R8uZleQPZ
    ZrDHZ4MhM2lsgK+tGKpB+MBcem/fm2fmMLGdDysgvqKewvA+qBGQ8GX7ZextnwK4
    jtPKHj04BjSjKsCqpAV3iUWCei2FDcgLPgA2tZFyCQKcg3WO9zjo3WaD/1nEjg2t
    0AP3wvMYpPRH0Q8xNct8OT8fd6+8k9R9M76wnf6vnunT7afZWSuOS/JRBTxygEFb
    S0TBb5nxEGB5yoTTyQxqbwJpKao7Y2vMxSlE5lIFzW8Dimw4+621rkEd/J7e04ti
    K4eCRoDCMwIDAQABo2AwXjAPBgNVHRMBAf8EBTADAQH/MEsGA1UdAQREMEKAEEkJ
    MEsDrm0cEPLqgfskslShHDAaMRgwFgYDVQQDEw9BaXJoZWFkIFJvb3QgQ0GCEPuE
    FsjnjRqpRFIKM5r1kyUwCQYFKw4DAh0FAAOCAQEAQc+O+h4NBBBmiua8+ykDrOWR
    AW4P78BYF80TBnora1zjeEwUWG1KM5L9fZzRhUaeFllPpgv4N9lJ/3fC0YNdMMQE
    X6jYJz78Hr05PoG5vWvLeAGufqysHNNcPKVH8R7MmP+TdP/FHcxhMQrpEKVHzk0d
    1FIplZQ4gEujoUdxMnWsAHc63GjT9vH4wxv4Lgb/Z6IBx1hWr1MElCerxAErlAd4
    iLlBqdbD7+TB2Ee/BHZyPxjVigK1QtnlrFaTANxoGUwWUkd2QXsJdAZ/eFYGGKby
    RjZNDXV1OtMfyqVGmYqMpcJRnh7fa3mxdzqnPpiXuQbRKjK5WGaFzuQztTV1Fw==
    -----END CERTIFICATE-----
  crt: |
    -----BEGIN CERTIFICATE-----
    MIIDozCCAougAwIBAgIRANRK7pHiipEyzOQcHlvw6bUwDQYJKoZIhvcNAQELBQAw
    LjEsMCoGA1UEAxMjQWlyaGVhZCBEZXZlbG9wbWVudCBJbnRlcm1lZGlhdGUgQ0Ew
    HhcNMjEwMTI4MDk1MDU5WhcNMzEwMTI2MDk1MDU5WjAYMRYwFAYDVQQDDA1lbGFz
    dGljc2VhcmNoMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz/ejKbTE
    I2+0SAzUwnUG+5XLxD1aWrSlEPmqCv12sGsn5GoOMcLWsWeArbrE5bnAsF7/r/NO
    rKf44evniiFw19hGCIMi7tuMicJQ44yli9FW4NvEIm/0wd+vhuwz1AKivcO4pZ4N
    3fjxQo3hEjGDNBo5UJfvWY4sc5qed89dEdEL51w3xbcFZY6wsoOgVlCwGyeyRU8V
    BBH1fuJ5zpWfBIb/mkSHM/gqe++iB13oqjiV9QWiz8jniJHvToTK8IJY1qDNNRxb
    FpKnik1Kj5l5IdK4vVx1kWoKJrmaADl8S4kWWBX1+3iFmmVKRURYXwSnBbm4UtD6
    OdbLX2EkJ7QFrwIDAQABo4HRMIHOMAkGA1UdEwQCMAAwHQYDVR0OBBYEFIsH/ERW
    KeMl7q/DYhNeQLIKmPrIMDsGA1UdIwQ0MDKhHqQcMBoxGDAWBgNVBAMTD0Fpcmhl
    YWQgUm9vdCBDQYIQlJertiCFn4BKs57+T7k0YTATBgNVHSUEDDAKBggrBgEFBQcD
    ATALBgNVHQ8EBAMCBaAwQwYDVR0RBDwwOoIVZWxhc3RpY3NlYXJjaC1lcy1odHRw
    giFlbGFzdGljc2VhcmNoLWVzLWh0dHAuZGVmYXVsdC5zdmMwDQYJKoZIhvcNAQEL
    BQADggEBAHZa2xHsHbHER0uz12zkaILhloJGA4Gx0UJ6ZvjCDfcQIYWcKrFgrMKQ
    HlSfTq1XlvelzHUolBtp0Sd/pbQVXsjMHJjZXDUblQKizhFETNkd7qnl24YrROxx
    HNpm/DfkGW/9tl/IMMNwyBxvEnBDV9JsL5DmjpAwLJ123w+GpOg9tgsLdJwDqqZL
    AjC8M9gfh14NXzqocntRomQl5aF5U7oHSek8HSppSi77FinE/w3cJZtIs90smAvs
    m834mpo/g/2jN8OCqocZPk+1iGg7jYdF3jKrwCjpwgeGso2Mt3/q/VehQudB6ePA
    pb79CYnyAHZiuzZbnMgz7ku7ubm6U1U=
    -----END CERTIFICATE-----
  key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEAz/ejKbTEI2+0SAzUwnUG+5XLxD1aWrSlEPmqCv12sGsn5GoO
    McLWsWeArbrE5bnAsF7/r/NOrKf44evniiFw19hGCIMi7tuMicJQ44yli9FW4NvE
    Im/0wd+vhuwz1AKivcO4pZ4N3fjxQo3hEjGDNBo5UJfvWY4sc5qed89dEdEL51w3
    xbcFZY6wsoOgVlCwGyeyRU8VBBH1fuJ5zpWfBIb/mkSHM/gqe++iB13oqjiV9QWi
    z8jniJHvToTK8IJY1qDNNRxbFpKnik1Kj5l5IdK4vVx1kWoKJrmaADl8S4kWWBX1
    +3iFmmVKRURYXwSnBbm4UtD6OdbLX2EkJ7QFrwIDAQABAoIBAB0iRvRHw5ZnRq01
    RvT66gCCqqoSIj9EwT8QirbBbUgnqs3/4X8tGWB+7HLqED1SeWD73fvrLOFZIq+b
    mbMrHiDOxnjYziMCFL0TwLsv790XdYFIqEBeyL4ENRXErzoLKHtHGO3yp2SqRDob
    oCUpVIUPC2pz7m7wUN/dEEgef55IFv165LA5gLAq7QSjgZHmmW9SfbN4q4I6nMsV
    2oADDlrIAzhtowqcyIMtv2/tKCsgTszw2Gu/u2+2IwiLXNasfIXSnXBG+yo4xAm4
    IxwPAwlaxT/m56dv08MajMg6mWyTVMmHlGR+c2o6SXEda3R9c8+X5VXtwoCZ7MVF
    GFIYtykCgYEA+EJ5G23WYSm50KYgzdAZ/Wr/fDaU58/PmRUj7UtMTljzIT7zu4Gg
    jPAQLFA5zYHUYvs3QfhPiLjFChm7UvgDHtxxzdgjXuaVZKS9Dtes7sjwsdNwpZIs
    9S50p8n+2a8n29aRY+NuzkTbLTNB5yvFJsHjzRa4kygpxC9GBkWYNkMCgYEA1nOQ
    blFnNeg/PwhFwwJ1ZiZNYSOLx1kP8loch0ZC62a4+1DHkSlwNJC+ynaEm9xlJjK6
    A1vq0uguvwrWwisKf/wMRmntQvp7gud0YducmGPuI7oKYqfWduYxJuPn4tmXXlcf
    22XkvrRTDXG88K/Vutjo8AH7q5/7dFjZBBXjOiUCgYEAzxByfsRAGM56o2LM3Z0C
    8HG8IlhMHoUf++i8DIHPZVGfiE0/cVePF75rXuqTK6tsABrUXfvEKp8iCWio62zc
    /XKUoUHzToY4eLdG0QhmvstupoNa415mjSFwPzqli98h+aSfo5bgpr6bqLml8DB7
    wfXaEQcwb90B6RYc68JEUI0CgYEAguHZHls0QKRUJWYpHZGckRGDXGvTXYEvyFvS
    2YS6Ru1UrJ1qj1/ZCVvl9a9L08w5N4zyFia9NKdcEGDPHYYjTGVKIJd5pM03IHee
    gjMEacVjjA55VCjXLY3kJbYmyj6+sWc/HCod534qyiPGiqbmLLlBwWmUbfSgBSxM
    lr+9BLkCgYEA9BonEB9DDglzKeBr/euY123l7Z+t6VOGWmK8cR19us1BU9L3sK53
    1N99hxaSy4Xq4R2DCi/8drOmv4pmoudyK1TlvN/PAk5Ij2oZWLhU0C1jtLAiqeQr
    umC7iJgPeGjEBJRjSAt5exNPSksrdb7qcRBnqLWA/MHAh0n6MfOiDms=
    -----END RSA PRIVATE KEY-----
elasticsearch_version: 7.10.2
load_balancer_ip: 192.168.225.53
