---
apiVersion: couchbase.com/v2
kind: CouchbaseEphemeralBucket
metadata:
  name: cache
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
spec:
  memoryQuota: 2048Mi
---
apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: data
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
spec:
  memoryQuota: 2048Mi
