---
apiVersion: v1
kind: Secret
metadata:
  name: couchbase-server-auth
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
type: Opaque
data:
  username: {{ .Values.admin.username | b64enc }}
  password: {{ .Values.admin.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: couchbase-server-tls
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
type: Opaque
data:
  chain.pem: {{ .Values.certificates.crt | b64enc }}
  pkey.key: {{ .Values.certificates.key | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: couchbase-operator-tls
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
type: Opaque
data:
  ca.crt: {{ .Values.certificates.ca | b64enc }}
