- name: Apply operator
  k8s:
    definition: "{{ lookup('url', 'https://download.elastic.co/downloads/eck/{{ eck_operator_version }}/all-in-one.yaml', split_lines=False) | from_yaml_all }}"
    wait: yes
    state: present
