- name: Get Kubernetes base64 version
  shell: kubectl version | base64 | tr -d '\n'
  register: kube_base64_version
  changed_when: no
  when: init_cluster.changed

- name: Install Weave Net
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version={{ kube_base64_version.stdout }}"
  when: init_cluster.changed
