- name: Create vsphere.conf file
  template:
    src: "{{ role_path }}/templates/etc/kubernetes/vsphere.conf.j2"
    dest: /etc/kubernetes/vsphere.conf
    mode: "0644"
    owner: root
    group: root
  become: yes
