- name: Get Ca file stats
  stat:
    path: /etc/kubernetes/pki/ca.key
  register: kube_ca

- name: Copy init.yml file
  copy:
    src: "{{ role_path }}/files/etc/kubernetes/init.yml"
    dest: /etc/kubernetes/init.yml
    mode: 0644
    owner: root
    group: root
  when: not kube_ca.stat.exists
  become: yes

- name: Init cluster
  shell: kubeadm init --config /etc/kubernetes/init.yml
  register: init_cluster
  when: not kube_ca.stat.exists
  become: yes

- name: Create .kube directory
  file:
    path: $HOME/.kube
    mode: 0755
    state: directory
  register: kube_dir
  when: init_cluster.changed

- name: Copy config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ kube_dir.path }}/config"
    remote_src: yes
    owner: "{{ kube_dir.owner }}"
    group: "{{ kube_dir.group }}"
  when: init_cluster.changed
  become: yes
