- name: Install Metal Lb
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v{{ metal_lb_version }}/manifests/namespace.yaml
    kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v{{ metal_lb_version }}/manifests/metallb.yaml
    kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
  when: init_cluster.changed

- name: Copy Metal Lb config map
  copy:
    src: "{{ role_path }}/files/tmp/metal_lb_config.yml"
    dest: /tmp/metal_lb_config.yml
  register: metal_lb_config_file

- name: Configure Metal Lb
  shell: kubectl apply -f {{ metal_lb_config_file.dest }}
