- name: Copy daemon.json file
  copy:
    src: "{{ role_path }}/files/etc/docker/daemon.json"
    dest: /etc/docker/daemon.json
    mode: 0644
    owner: root
    group: root
  notify: Reload Docker
  become: yes
