- name: Create temp directory
  file:
    path: "/tmp/{{ role_name }}"
    state: directory
  register: directory
  tags:
    - deploy
    - destroy

- name: Create values file
  template:
    src: "{{ role_path }}/templates/tmp/{{ role_name }}/values.yaml.j2"
    dest: "{{ directory.path }}/values.yaml"
  tags:
    - deploy
    - destroy

- name: Apply chart
  shell: "helm upgrade {{ role_name }} -f /tmp/{{ role_name }}/values.yaml {{ role_name }} --install --version v{{ homebridge_version }} --repo https://k8s-at-home.com/charts/"
  tags:
    - deploy

- name: Delete chart
  shell: "helm uninstall {{ role_name }}"
  tags:
    - destroy

- name: Delete temp directory
  file:
    path: "{{ directory.path }}"
    state: absent
  register: directory
  tags:
    - deploy
    - destroy
