- name: Get chart status
  shell: helm status coredns
  check_mode: no
  changed_when: no
  failed_when: no
  register: status
  tags:
    - deploy
    - destroy

- name: Create temp directory
  file:
    path: "/tmp/{{ role_name }}"
    state: directory
  register: directory
  tags:
    - deploy
    - destroy

- name: Copy chart directory
  copy:
    src: "{{ role_path }}/files/tmp/{{ role_name }}/"
    dest: "{{ directory.path }}"
    directory_mode: 0755
  tags:
    - deploy
    - destroy

- name: Create Chart.yaml
  template:
    src: "{{ role_path }}/templates/tmp/{{ role_name }}/Chart.yaml.j2"
    dest: "{{ directory.path }}/Chart.yaml"
  tags:
    - deploy
    - destroy

- name: Apply chart
  shell: "helm {{ 'upgrade' if status.rc == 0 else 'install' }} coredns {{ directory.path }}"
  tags:
    - deploy

- name: Delete chart
  shell: helm uninstall coredns
  tags:
    - destroy

- name: Delete temp directory
  file:
    path: "{{ directory.path }}"
    state: absent
  register: directory
  tags:
    - deploy
    - destroy
