---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns-external
  labels:
    app.kubernetes.io/name: coredns-external
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: coredns-external
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: coredns-external
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
      annotations:
        checksum.config: {{ include (print $.Template.BasePath "/configmap.yml") . | sha256sum | trunc 63 }}
    spec:
      containers:
        - name: coredns-external
          image: coredns/coredns:{{ .Chart.AppVersion }}
          args: [ "-conf", "/etc/coredns/Corefile" ]
          ports:
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 53
              name: dns-udp
              protocol: UDP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8181
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          volumeMounts:
            - mountPath: /etc/coredns/Corefile
              name: config
              subPath: Corefile
            {{- range $path, $d := .Files.Glob "zones/**" }}
            - mountPath: /etc/coredns/{{ index ($path | splitList "/") 1 }}
              name: zones
              subPath: {{ index ($path | splitList "/") 1 }}
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: coredns-external-config
        - name: zones
          configMap:
            name: coredns-external-zones
