---
apiVersion: v1
kind: Service
metadata:
  name: coredns-external-tcp
  labels:
    app.kubernetes.io/name: coredns-external
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    metallb.universe.tf/allow-shared-ip: coredns-external
spec:
  selector:
    app.kubernetes.io/name: coredns-external
  type: LoadBalancer
  loadBalancerIP: 192.168.225.29
  externalTrafficPolicy: Local
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: coredns-external-udp
  labels:
    app.kubernetes.io/name: coredns-external
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    metallb.universe.tf/allow-shared-ip: coredns-external
spec:
  selector:
    app.kubernetes.io/name: coredns-external
  type: LoadBalancer
  loadBalancerIP: 192.168.225.29
  externalTrafficPolicy: Local
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
