---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-internal-config
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.AppVersion }}
data:
  Corefile: |
    .:53 {
      acl {
        allow net 192.168.225.0/24
        block
      }
      loop
      forward . 127.0.0.1:5053
      cache 30
      prometheus :9153
      log
      errors
      health
      ready
    }
    {{- range $path, $data := .Files.Glob "zones/**" }}
    {{ trimPrefix "db." (index ($path | splitList "/") 1) }} {
      file /etc/coredns/{{ index ($path | splitList "/") 1 }}
    }
    {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-internal-zones
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.AppVersion }}
data:
  {{- range $path, $data := .Files.Glob "zones/**" }}
  {{ index ($path | splitList "/") 1 }}: |-
  {{- $data | toString | nindent 4 }}
  {{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pi-hole-custom-dnsmasq
data:
  02-custom.conf: |
    port=5053
