---
apiVersion: v1
kind: Service
metadata:
  name: coredns-internal-tcp
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
  annotations:
    metallb.universe.tf/allow-shared-ip: coredns-internal
spec:
  selector:
    app: {{ .Chart.Name }}
  type: LoadBalancer
  loadBalancerIP: 192.168.225.26
  externalTrafficPolicy: Local
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: coredns-internal-udp
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
  annotations:
    metallb.universe.tf/allow-shared-ip: coredns-internal
spec:
  selector:
    app: {{ .Chart.Name }}
  type: LoadBalancer
  loadBalancerIP: 192.168.225.26
  externalTrafficPolicy: Local
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
