domain: ENC[AES256_GCM,data:96xBd70EPoUjEii9tw==,iv:JzPnGhhyeqDQFQVYDPp6CuA/S+OPbnXpNOQ/Ry+bKYo=,tag:2zphWQ/ixXz/fcevHV4q6w==,type:str]
kube_worker_count: ENC[AES256_GCM,data:8A==,iv:m376+3uH5lzyUfZyg4Y0WiOHa4gH/IbwWP99+Ny+UA8=,tag:yBEZwZQGCrl//3LBMRQi0w==,type:int]
network_cidr: ENC[AES256_GCM,data:MSjyICNIXzVBihWA7s/ejg==,iv:sGBjNsHNk2md7G0r9EbFTlRU75CDUnUUBSEfpyC/0Ao=,tag:AdotkJi0gmkugak/I55drg==,type:str]
network_default_gateway: ENC[AES256_GCM,data:Z9j2jICa5HTAzIfkvA==,iv:hG4kEQ6TE0f67zgjffH9Lquj51ioaw9cAyfKe7ex1JU=,tag:czs1ruYdjRwsSWtkmRVVbQ==,type:str]
network_dns_servers:
- ENC[AES256_GCM,data:KataQ3frQbdnWZv4Jg==,iv:h5R5QZcqoeqFHSyffMLm1N7LFRap6bpFn9PIhk5+zh0=,tag:rp+fOaVfhjcdmBu19U47SQ==,type:str]
vcenter_datacenter: ENC[AES256_GCM,data:pC92RQ==,iv:9NhYhplmEpjsjzfHEoWdLxWrdntja2QTYUQeGcFHb8g=,tag:dQeSGskHv3azVqgX3NePWw==,type:str]
vcenter_datastore: ENC[AES256_GCM,data:3KyQMsjH+mXDzA==,iv:edj6hUiSRsTcIxNYEWWkjS6FfywMR5kd/8orVwGcfAY=,tag:/v/CHMgVDxd4IWZugOjTMw==,type:str]
vcenter_network: ENC[AES256_GCM,data:2XUZjU1OhvKgew==,iv:FRC99+tU8q1ZQ7tgWYqR25CIB9rMyem6wsXtdGCp/YA=,tag:wiq7+R+2UfGObtRflKcZeQ==,type:str]
vcenter_password: ENC[AES256_GCM,data:sfUUZH9RQ+I3iG6Rtg==,iv:OKKAYz79WxWMPGqChDnweXEHHNuDBatGHmhrCfxf9UA=,tag:Gp2oPEbR0k8mJrCGs34q1Q==,type:str]
vcenter_server: ENC[AES256_GCM,data:sTRa2DWlmclv51mE4jlxypL0QeXUOTg=,iv:rIFLfnZomCITBUUmAKzSPg/P5KR8drm3R19Ikt8beGk=,tag:IDl5mDwUFNkLCF+yarHyig==,type:str]
vcenter_storage_policy: ENC[AES256_GCM,data:akSqwjgosCN3qBAO/xTeqNkikOg=,iv:wVz1U4SiAqMhGpQtq/YH6paLJIB+rGgvtyfpffuM0uo=,tag:5ccUnWMBRFQsssj6qMW0Iw==,type:str]
vcenter_username: ENC[AES256_GCM,data:pH/huPyMvh7/i9TJU0oGPhnv3qReDU55Q7kw,iv:JUt3scAA0Zt8cH+Ds97vT61rbzt0JwSEhNFojSoLebE=,tag:tnOFM94tBOImyjn4s4Vvpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-06-23T21:12:15Z'
    mac: ENC[AES256_GCM,data:OoG5Rvaq1PwbySfYQigfdEDpvvLPt4ZSc+ay/jQU6qMr84Ki0/QwZK1oYQDjXZizEYQu3nGckHHNzCCdsAXveJGRhK9saSBnQgEW7nk5Z34xmKmDyI2uB6m9eXTn66Cy8VQpH8SBr7SivA+RnUbjV6JHgStWITyjsFcMuSRRGVw=,iv:u04wz14oPTTB++dUp90BK4vcfowNZTIK5SQQrxyOUgU=,tag:KXuLKF/bAuuwMdIdlH4x2w==,type:str]
    pgp:
    -   created_at: '2020-06-02T11:46:59Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA2U35XYo4cBrAQgAvIZynzwhlEEIjy9dajRPJPJaQNIa0CM86lxjPWRMJDTd
            xFGHnSH5x3d7WJfR576GyogICMX1bZwaCivzYUM/CE/YIDi2vQPp4VBkdSTj2wnp
            f3VbNCLfJHGnbbF7uw8vOkQ+/oGQPtC7PsoOnGq1XuQiUOwnXJSnTAiPiJNNwjTv
            j2cOpluQNr1f5dXLMWv/VNbDdaBvIveyHFneWwqnExD1idUcymD29/SrWFaA3PC5
            8o+UGYPAR7FqE2r9IY1gLU01KuRMTMshJyblasnGTohy+4bJdJaIIOqMP1whroBB
            UDVN6limEl3yUv6qZytuyUF9cOs6DJJsjlQkHVTRgtJcAbF99CN9vQAW3anGyPcm
            ByDEbqn5c+Dx2OyT8UIN7RDImpFMj9MnJMJ4soaICCt+Equ/9g7PxNRJF066cX8o
            ahRpl0AaZD3JJrsshlg3xYaiPynu/gUKCadyTaU=
            =R0kb
            -----END PGP MESSAGE-----
        fp: 765CCA6474657CF206CAACCB19F606777E114C68
    unencrypted_suffix: _unencrypted
    version: 3.5.0
