- name: Get repos
  shell: helm repo list
  check_mode: no
  changed_when: no
  failed_when: no
  register: repo_list

- name: Add stable repo
  shell: helm repo add stable https://kubernetes-charts.storage.googleapis.com
  when: repo_list.stdout.find('stable') == -1

- name: Add k8s-at-home repo
  shell: helm repo add k8s-at-home https://k8s-at-home.com/charts/
  when: repo_list.stdout.find('k8s-at-home') == -1

- name: Update repos
  shell: helm repo update
  check_mode: no
  changed_when: no
  failed_when: no
