- name: Apply manifest
  k8s:
    definition: "{{ lookup('url', 'https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml', split_lines=False) | from_yaml_all }}"
    wait: yes
    state: present
