- name: Download Flannel manifest
  get_url:
    url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    dest: /tmp/kube-flannel.yml
  register: flannel_manifest

- name: Apply Flannel manifest
  k8s:
    src: "{{ flannel_manifest.dest }}"
    wait: yes
    state: present
